name: Build LiaScript to SCORM and PDF

on:
  push:
    branches:
      - main # Or your default branch, e.g., master
    paths:
      - 'Test 01.md' # Trigger only when Test 01.md changes
      - 'package.json' # Also trigger if package.json changes
      - 'scripts/generate-pdf.js' # Also trigger if the script changes
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build_assets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Or a version compatible with your dependencies

    - name: Install Node.js dependencies (including Puppeteer, Express, and potentially LiaScript Exporter)
      run: npm install # This will install all dependencies listed in package.json

    # --- SCORM Generation Steps ---
    - name: Convert LiaScript to SCORM
      # Now we run the script defined in package.json
      run: npm run export-scorm

    - name: Upload SCORM package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: scorm-package
        path: liascript_course.zip # This path must match the output of your export-scorm script

    # --- PDF Generation Steps ---
    - name: Generate PDF from LiaScript
      run: node scripts/generate-pdf.js

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: liascript-pdf
        path: liascript_course.pdf # This path matches the output in generate-pdf.js

    - name: Create a release (Optional - for easier distribution)
      if: github.ref == 'refs/heads/main' # Only create a release on pushes to main
      uses: softprops/action-gh-release@v2
      with:
        files: |
          liascript_course.zip
          liascript_course.pdf
        name: Course Assets - ${{ github.sha }}
        tag_name: assets-v${{ github.run_number }}
        body: |
          Automated SCORM package and PDF build for commit ${{ github.sha }}.
          [View Course](https://github.com/AEMSabbirRifat/Practice-Course/blob/${{ github.sha }}/Test%2001.md)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
